name: Build APK
on: [push, workflow_dispatch]

jobs:
  build:
    # Humne version 22.04 lock kar diya hai jisme saare packages mil jayenge
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install System Dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential git python3 python3-dev ffmpeg libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev libportmidi-dev libswscale-dev libavformat-dev libavcodec-dev zlib1g-dev libgstreamer1.0-dev gstreamer1.0-plugins-base gstreamer1.0-plugins-good libgstreamer-plugins-base1.0-dev libffi-dev libssl-dev autoconf automake libtool pkg-config cmake libncurses5-dev libncursesw5-dev libtinfo5 gettext libltdl-dev zip unzip openjdk-17-jdk lld

      - name: Install Buildozer & Cython
        run: |
          pip install --user --upgrade buildozer Cython==0.29.33
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Build with Buildozer
        run: |
          # Isme 15-20 minute lagenge
          buildozer android debug
        env:
          ACCEPT_SDK_LICENSE: "True"

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Attendance-App-APK
          path: bin/*.apk
