name: Build APK
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Essential Dependencies
        run: |
          sudo apt update
          # Sirf wahi packages jo Kivy aur Android build ke liye 100% zaruri hain
          sudo apt install -y build-essential git python3-pip zip unzip openjdk-17-jdk \
          libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev \
          autoconf libtool pkg-config zlib1g-dev

      - name: Install Buildozer & Cython
        run: |
          pip install --user --upgrade buildozer Cython==0.29.33
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Build with Buildozer
        run: |
          # Pehli baar build hone mein 20-25 mins lagte hain, sabr rakhein
          buildozer android debug
        env:
          ACCEPT_SDK_LICENSE: "True"

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Final-Attendance-App
          path: bin/*.apk
